name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress E2E Test cases
        run: cypress:run
    with:
      build: npm run build
      start: npm start
