name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Create project build
      - name: create build of project
        run: npm run build
      # Starte server and test
      - name: Start server and test
        run: npm run testing
